/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package threefactoratm;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static threefactoratm.Register.name;

/**
 *
 * @author Azure
 */
public class PuzzleFrame extends javax.swing.JInternalFrame {

    String imgpath;

    /**
     * Creates new form PuzzleFrame
     */
    public PuzzleFrame(String id) throws IOException {
        initComponents();

        String path = "src/images/image1/" + id + ".jpg";

        imgpath = path;

        BufferedImage bufferedImage = ImageIO.read(new File(path));
        Image aux = bufferedImage.getScaledInstance(342, 172, 1);
        jLabel1.setIcon(new ImageIcon(aux));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Puzzle Image");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Your Puzzle Image"));

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 287, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s1 = "D:/Server1/Puzzle/";
       // String s2 = "D:/Server2/Puzzle/";

        File filestorage1 = new File("D:/Server1/");
       // File filestorage2 = new File("D:/Server2/");

        if (!filestorage1.exists()) {
            filestorage1.mkdir();
        }

        //if (!filestorage2.exists()) {
       //     filestorage2.mkdir();
       // }

        File filesto1 = new File(s1);
       // File filesto2 = new File(s2);

        if (!filesto1.exists()) {
            filesto1.mkdir();
        }

       // if (!filesto2.exists()) {
       //     filesto2.mkdir();
       // }

        String outpathorg1 = s1 + SecureKey.genid + "_Puzzle.jpg";
       // String outpathorg2 = s2 + SecureKey.genid + "_Puzzle.jpg";

        String outpathorg1enc = s1 + SecureKey.genid + "_Puzzle_enc.jpg";
       // String outpathorg2enc = s2 + SecureKey.genid + "_Puzzle_enc.jpg";

        try {

            azUtil.EncDcy.encrypt(SecureKey.passPhrase, imgpath, outpathorg1enc);
          //  azUtil.EncDcy.encrypt(SecureKey.passPhrase, imgpath, outpathorg2enc);

            SecureKey.writeFile(imgpath, outpathorg1);
          //  SecureKey.writeFile(imgpath, outpathorg2);

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/atm", "root", "root");

            String sql = "insert into puzzle(user_id,  pz_image)" + "values(?,?)";

            PreparedStatement stm = con.prepareStatement(sql);

            String tempath = SecureKey.genid + "_Puzzle_enc.jpg";

            stm.setInt(1, SecureKey.genid);
            stm.setString(2, tempath);

            stm.execute();

            con.close();

            FingerPrint log = new FingerPrint();
            Dimension desktopSize = getDesktopPane().getSize();
            Dimension jInternalFrameSize = log.getSize();
            log.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                    (desktopSize.height - jInternalFrameSize.height) / 2);
            getDesktopPane().add(log);
            log.setVisible(true);

            dispose();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
